# Auto-generated by scripts/drawio_to_fsm.py
from typing import Optional
from hsim.core.fsm.FSM import FSM
from hsim.core.fsm.states import State
from hsim.core.fsm.transitions import Transition, MessageTransition, TimeoutTransition

class Statemachine(FSM):
    # original_id: container
    class Idle(State):
        # original_id: F7J8uRpZ7DqpZP_RapBQ-7
        def __init__(self, name, fsm, initial_state=False):
            super().__init__(name, fsm, initial_state)
        def on_enter(self):
            pass

    class Working(State):
        # original_id: TbzG5wrwrJmqIxwP26u2-1
        def __init__(self, name, fsm, initial_state=False):
            super().__init__(name, fsm, initial_state)
        def on_enter(self):
            pass

    Trans_Idle_to_Working = Transition.define(Idle, Working)
    Trans_Working_to_Idle = Transition.define(Working, Idle)

def make_statemachine(env):
    return Statemachine(env)
