#!/usr/bin/env python3
"""
Parse a draw.io XML file and generate a simple Python FSM module.

Usage:
  python scripts/drawio_to_fsm.py --input path/to/a.drawio.xml --output path/to/generated_fsm.py

The script looks for `mxCell` elements with `vertex="1"` (states) and `edge="1"` (transitions).
If a state's `style` attribute contains `code=...` that value is URL-encoded and will be decoded and inserted
as the state's `on_entry` function body.
"""
import argparse
import xml.etree.ElementTree as ET
from urllib.parse import unquote
import html
import sys


def parse_drawio(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    # mxCell elements can be nested; collect all
    cells = root.findall('.//mxCell')

    states = {}
    transitions = []
    container_ids = []
    container_names = {}

    for c in cells:
        attrib = c.attrib
        # Identify vertex (state) nodes
        if attrib.get('vertex') == '1':
            cid = attrib.get('id')
            # value may contain HTML entities; decode
            value = attrib.get('value') or ''
            value = html.unescape(value)
            # name fallback to id if value empty
            name = value.strip() or cid

            # parse style for code=... entry (style uses semicolon-separated key/value)
            style = attrib.get('style') or ''
            # detect swimlane (container)
            if 'swimlane' in style:
                container_ids.append(cid)
                container_names[cid] = name
                # still record as container but do not treat as a state below
                # continue to next cell
                # (we don't 'continue' because we want to capture any code=value on the swimlane)
            
            code_body = None
            for part in style.split(';'):
                if part.startswith('code='):
                    raw = part[len('code='):]
                    # draw.io encodes newlines and special chars in URL-encoded form
                    code_body = unquote(raw)
                    break

            # If this cell is a swimlane (container), record its code but don't create a state entry
            if cid in container_ids:
                # store container code if needed
                states.setdefault(cid, {'id': cid, 'name': name, 'code': code_body, 'is_container': True})
            else:
                states[cid] = {'id': cid, 'name': name, 'code': code_body}

        # Identify edges (transitions)
        if attrib.get('edge') == '1':
            src = attrib.get('source')
            tgt = attrib.get('target')
            label = attrib.get('value') or ''
            transitions.append({'source': src, 'target': tgt, 'label': html.unescape(label)})

    # choose primary container name if present
    container_name = None
    if container_ids:
        # prefer first container
        cid = container_ids[0]
        container_name = container_names.get(cid) or states.get(cid, {}).get('name')
    return container_name, states, transitions


def safe_state_name(name):
    # Produce a valid Python identifier from name
    s = ''.join(ch if ch.isalnum() else '_' for ch in name).strip('_')
    if not s:
        s = 'state'
    if s[0].isdigit():
        s = '_' + s
    return s


def generate_module(states, transitions, out_path, module_name='generated_fsm', container_name=None):
    # Map ids to safe python class names
    id_to_class = {}
    # If a container ID was present in states (marked), remove it from states
    # container entries will have 'is_container' key
    states = {k: v for k, v in states.items() if not v.get('is_container')}

    for cid, s in states.items():
        cls = safe_state_name(s['name'])
        # avoid duplicates
        base = cls
        i = 1
        while cls in id_to_class.values():
            cls = f"{base}_{i}"
            i += 1
        id_to_class[cid] = cls

    lines = []
    lines.append('# Auto-generated by scripts/drawio_to_fsm.py')
    lines.append('from typing import Optional')
    lines.append('from hsim.core.fsm.FSM import FSM')
    lines.append('from hsim.core.fsm.states import State')
    lines.append('from hsim.core.fsm.transitions import Transition, MessageTransition, TimeoutTransition')
    lines.append('')

    # Create a container Statemachine class that inherits from FSM and contains nested State and Transition classes
    if not container_name:
        container_name = 'Statemachine'
    lines.append(f'class {container_name}(FSM):')
    lines.append(f"    # original_id: container")

    # Nested State classes
    for cid, s in states.items():
        cls = id_to_class[cid]
        lines.append(f'    class {cls}(State):')
        lines.append(f"        # original_id: {cid}")
        lines.append(f"        def __init__(self, name, fsm, initial_state=False):")
        lines.append(f"            super().__init__(name, fsm, initial_state)")

        code_body = s.get('code')
        if code_body:
            code_body = code_body.replace('\r\n', '\n').replace('\r', '\n')
            # extract body lines (skip def on_entry if present)
            if 'def on_entry' in code_body:
                parts = code_body.split('\n')
                body_lines = parts[1:]
            else:
                body_lines = code_body.split('\n')

            # compute minimal indentation
            min_indent = None
            for ln in body_lines:
                stripped = ln.lstrip()
                if not stripped:
                    continue
                indent = len(ln) - len(stripped)
                if min_indent is None or indent < min_indent:
                    min_indent = indent
            if min_indent is None:
                min_indent = 0

            lines.append('        def on_enter(self):')
            for ln in body_lines:
                if not ln.strip():
                    lines.append('            pass')
                else:
                    trimmed = ln[min_indent:]
                    lines.append(f'            {trimmed}')
        else:
            lines.append('        def on_enter(self):')
            lines.append('            pass')

        lines.append('')

    # Nested Transition classes using define
    transition_class_names = []
    for idx, t in enumerate(transitions):
        src = t['source']
        tgt = t['target']
        label = t['label'].strip()
        src_cls = id_to_class.get(src)
        tgt_cls = id_to_class.get(tgt)
        if not src_cls or not tgt_cls:
            continue
        tname = f'Trans_{safe_state_name(states[src]["name"]) }_to_{safe_state_name(states[tgt]["name"]) }'
        base_tname = tname
        i = 1
        while tname in transition_class_names:
            tname = f"{base_tname}_{i}"
            i += 1
        transition_class_names.append(tname)

        # Add transition definition inside class
        if label:
            # numeric => TimeoutTransition
            try:
                float(label)
                is_numeric = True
            except Exception:
                is_numeric = False
            if is_numeric:
                lines.append(f'    {tname} = TimeoutTransition.define({src_cls}, {tgt_cls})')
                lines.append(f'    {tname}._timeout = {label}')
            else:
                escaped = label.replace("'", "\\'")
                lines.append(f"    {tname} = MessageTransition.define({src_cls}, {tgt_cls})")
                lines.append(f"    {tname}._message = '{escaped}'")
        else:
            lines.append(f'    {tname} = Transition.define({src_cls}, {tgt_cls})')

    lines.append('')
    # Provide a factory
    lines.append(f'def make_{container_name.lower()}(env):')
    lines.append(f'    return {container_name}(env)')

    content = '\n'.join(lines) + '\n'

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f'Wrote generated module to: {out_path}')


def main(argv=None):
    p = argparse.ArgumentParser(description='Generate Python FSM from draw.io XML')
    p.add_argument('--input', '-i', required=True, help='Path to draw.io XML file')
    p.add_argument('--output', '-o', required=True, help='Path to write generated Python module')
    args = p.parse_args(argv)

    container_name, states, transitions = parse_drawio(args.input)
    if not states:
        print('No states found in the XML file.', file=sys.stderr)
        sys.exit(2)
    generate_module(states, transitions, args.output, container_name=container_name)


if __name__ == '__main__':
    main()
